import feedparser
import datetime

# 取得したいITニュースのRSSフィードリスト
RSS_URLS = [
    "https://jp.techcrunch.com/feed/",
    "https://www.itmedia.co.jp/news/rss/2.0/news_bursts.xml",
    "https://publickey1.jp/atom.xml"
]

def fetch_news():
    news_items = []
    for url in RSS_URLS:
        feed = feedparser.parse(url)
        for entry in feed.entries[:5]: # 各サイト上位5件
            news_items.append({
                'title': entry.title,
                'link': entry.link,
                'date': entry.get('published', '不明')
            })
    return news_items

def generate_html(news_items):
    now = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    html_content = f"""
    <!DOCTYPE html>
    <html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Daily IT News</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/water.css">
    </head>
    <body>
        <h1>今日（{now}）のITニュース</h1>
        <ul>
    """
    for item in news_items:
        html_content += f'<li><a href="{item["link"]}" target="_blank">{item["title"]}</a></li>'
    
    html_content += """
        </ul>
        <footer>Generated by GitHub Actions</footer>
    </body>
    </html>
    """
    
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

if __name__ == "__main__":
    items = fetch_news()
    generate_html(items)
